const GENERATION = {
    FETCH: 'GENERATION_FETCH',
    FETCH_ERROR: 'GENERATION_FETCH_ERROR',
    FETCH_SUCCESS: 'GENERATION_FETCH_SUCCESS',
};

const ITEM = {
    FETCH: 'ITEM_FETCH',
    FETCH_ERROR: 'ITEM_FETCH_ERROR',
    FETCH_SUCCESS: 'ITEM_FETCH_SUCCESS',
};

const ACCOUNT = {
    FETCH: 'ACCOUNT_FETCH',
    FETCH_ERROR: 'ACCOUNT_FETCH_ERROR',
    FETCH_SUCCESS: 'ACCOUNT_FETCH_SUCCESS',
    FETCH_LOGOUT_SUCCESS: 'ACCOUNT_FETCH_LOGOOUT_SUCCESS',
    FETCH_AUTHENTICATED_SUCCESS: 'ACCOUNT_FETCH_AUTHENTICATED_SUCCESS',
};

const ACCOUNT_ITEMS = {
    FETCH: 'ACCOUNT_ITEM_FETCH',
    FETCH_ERROR: 'ACCOUNT_ITEM_FETCH_ERROR',
    FETCH_SUCCESS: 'ACCOUNT_ITEM_FETCH_SUCCESS',
};

const ACCOUNT_INFO = {
    FETCH: 'ACCOUNT_INFO_FETCH',
    FETCH_ERROR: 'ACCOUNT_INFO_FETCH_ERROR',
    FETCH_SUCCESS: 'ACCOUNT_INFO_FETCH_SUCCESS',
};

const PUBLIC_ITEMS = {
    FETCH: 'PUBLIC_ITEMS_FETCH',
    FETCH_ERROR: 'PUBLIC_ITEMS_FETCH_ERROR',
    FETCH_SUCCESS: 'PUBLIC_ITEMS_FETCH_SUCCESS',
};

export { GENERATION, ITEM, ACCOUNT, ACCOUNT_ITEMS, ACCOUNT_INFO, PUBLIC_ITEMS };
